[build.environment]
NPM_FLAGS = "--version"

[build]
command = "(pnpm i && pnpm run build) || (npm install pnpm && pnpm i && pnpm run build)"

[[redirects]]
from = "/blog/*"
to = "https://blogbarbajoe.netlify.app/"
status = 200
force = false
