name: Publish css-lib to NPM
on:
  push:
    branches: main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: npm i && mkdir -p dist && npm run build:prod
        working-directory: src/packages/css-lib
      - uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_AUTH_TOKEN }}
          package: ./src/packages/css-lib/package.json
